import {
  DOCUMENTS_PROCESS_STATUS, PROFORMA_AUTHORIZATION_STATUS,
  PAID_DOCUMENTS_STATUS, READY_DOCUMENTS_STATUS, REQUESTED_OPERATION_STATUS,
  DRAFT_OPERATION_STATUS,
} from '../seeders';

export const customerCanDeleteFiles = (status: string) => [
  REQUESTED_OPERATION_STATUS, DRAFT_OPERATION_STATUS,
  DOCUMENTS_PROCESS_STATUS, PROFORMA_AUTHORIZATION_STATUS,
  PAID_DOCUMENTS_STATUS, READY_DOCUMENTS_STATUS].includes(status);
